version: "3.5"
services:
  crawla_web:
    build: .
    ports:
      - "3000:3000"
    volumes: 
      - ".:/work"
    networks:
      - crw
    restart: always
  chrome:
    image: "selenium/standalone-chrome:latest"
    ports:
      - "4444:4444"
    networks:
      - crw
    restart: always
  redis:
    image: redis:6.2-alpine
    networks:
      - crw
    restart: always

networks:
  crw:
    driver: bridge
