version: "3.4"
services:
  crawla_web:
    build: .
    ports:
      - "3000:3000"
    volumes: 
      - ".:/work"
    networks:
      - crw
  chrome:
    image: "selenium/standalone-chrome:latest"
    ports:
      - "4444:4444"
    networks:
      - crw

networks:
  crw:
    driver: bridge